import argparse
import os
import time
from dataclasses import dataclass
from typing import Dict, List, Optional, Sequence, Tuple

import h5py
import numpy as np
import torch
from tqdm.auto import tqdm

from fine_tuning import (
    RAGDataCollator,
    _to_str_doc_id,
    load_context_store,
    load_local_qa_splits,
    load_query_embedding_store,
    load_retriever,
)
from metrics import f1_single
from modeling_cocom import COCOM


@dataclass
class EvaluationArgs:
    model_name: str
    contexts_path: str
    embeddings_path: str
    docs_path: str
    queries_path: str
    answers_path: str
    query_embeddings_path: str
    top_k: int
    decoder_max_length: int
    max_new_tokens: int
    batch_size: int
    retriever_batch_size: int
    device: torch.device
    max_examples: Optional[int]
    split: str


@dataclass
class EvaluationInstance:
    feature: Dict[str, object]
    references: Sequence[str]
    query_id: str


class EvaluationError(RuntimeError):
    pass


def parse_args() -> EvaluationArgs:
    parser = argparse.ArgumentParser(
        description="Evaluate a Hugging Face hosted COCOM model on MS MARCO contexts produced by compress.py",
    )
    parser.add_argument("--model-name", required=True, help="Hugging Face repository id for the COCOM model")
    parser.add_argument(
        "--contexts-path",
        default="data/contexts/contexts.h5",
        help="Path to the compressed context store produced by compress.py",
    )
    parser.add_argument(
        "--embeddings-path",
        default="data/embeddings/embeddings.npz",
        help="Path to the FAISS document embeddings generated by compress.py",
    )
    parser.add_argument(
        "--docs-path",
        default="data/docs.json",
        help="Path to the flattened MS MARCO documents saved by compress.py",
    )
    parser.add_argument(
        "--queries-path",
        default="data/queries.json",
        help="Path to the queries JSON exported by compress.py",
    )
    parser.add_argument(
        "--answers-path",
        default="data/answers.json",
        help="Path to the answers JSON exported by compress.py",
    )
    parser.add_argument(
        "--query-embeddings-path",
        default="data/query_embeddings.npz",
        help="Path to the pre-computed query embeddings",
    )
    parser.add_argument("--top-k", type=int, default=5, help="Number of retrieved documents per query")
    parser.add_argument(
        "--decoder-max-length",
        type=int,
        default=256,
        help="Maximum decoder sequence length (affects prompt truncation)",
    )
    parser.add_argument(
        "--max-new-tokens",
        type=int,
        default=64,
        help="Number of new tokens to generate for each answer",
    )
    parser.add_argument("--batch-size", type=int, default=4, help="Generation batch size")
    parser.add_argument(
        "--retriever-batch-size",
        type=int,
        default=64,
        help="Batch size used when querying the FAISS retriever",
    )
    parser.add_argument(
        "--device",
        choices=["cpu", "cuda"],
        default="cuda" if torch.cuda.is_available() else "cpu",
        help="Device used for evaluation",
    )
    parser.add_argument(
        "--max-examples",
        type=int,
        default=None,
        help="Limit the number of evaluation examples (for quick smoke tests)",
    )
    parser.add_argument(
        "--split",
        choices=["train", "eval", "all"],
        default="eval",
        help="Which split from the local QA dataset to evaluate",
    )

    args = parser.parse_args()
    device = torch.device(args.device)

    return EvaluationArgs(
        model_name=args.model_name,
        contexts_path=args.contexts_path,
        embeddings_path=args.embeddings_path,
        docs_path=args.docs_path,
        queries_path=args.queries_path,
        answers_path=args.answers_path,
        query_embeddings_path=args.query_embeddings_path,
        top_k=max(1, args.top_k),
        decoder_max_length=max(8, args.decoder_max_length),
        max_new_tokens=max(1, args.max_new_tokens),
        batch_size=max(1, args.batch_size),
        retriever_batch_size=max(1, args.retriever_batch_size),
        device=device,
        max_examples=args.max_examples,
        split=args.split,
    )


def ensure_exists(path: str, description: str) -> None:
    if not os.path.exists(path):
        raise EvaluationError(f"{description} not found at {path}")


def clean_generated_text(text: str, tokenizer) -> str:
    cleaned = text
    special_attrs = ("ae_token", "mem_token", "enc_token", "sep_token")
    for attr in special_attrs:
        token = getattr(tokenizer, attr, None)
        if token:
            cleaned = cleaned.replace(token, "")
    return cleaned.strip()


def synchronize_if_needed(device: torch.device) -> None:
    if device.type == "cuda":
        torch.cuda.synchronize(device)


def select_examples(
    args: EvaluationArgs,
    retriever,
    query_vectors: Dict[str, np.ndarray],
    context_index: Dict[str, int],
) -> Tuple[List[EvaluationInstance], Dict[str, int]]:
    train_examples, eval_examples = load_local_qa_splits(args.queries_path, args.answers_path)

    if args.split == "train":
        raw_examples = train_examples
    elif args.split == "eval":
        raw_examples = eval_examples
    else:
        raw_examples = list(train_examples) + list(eval_examples)

    if not raw_examples:
        raise EvaluationError("No evaluation examples available after loading local QA splits")

    with h5py.File(args.contexts_path, "r") as context_file:
        contexts_ds = context_file["contexts"]
        shapes_ds = context_file["shapes"]

        pending_examples: List[Tuple[str, str, Sequence[str]]] = []
        pending_vectors: List[np.ndarray] = []

        instances: List[EvaluationInstance] = []
        skipped_embeddings = 0
        skipped_contexts = 0

        def process_pending() -> None:
            nonlocal pending_examples, pending_vectors, skipped_contexts
            if not pending_examples:
                return
            vectors = np.asarray(pending_vectors, dtype=np.float32)
            retrieved_batches = retriever.search_batch(vectors, k=args.top_k)
            for (query_id, question, answers), doc_ids in zip(pending_examples, retrieved_batches):
                context_tensors: List[torch.Tensor] = []
                for doc_id in doc_ids:
                    key = _to_str_doc_id(doc_id)
                    index = context_index.get(key)
                    if index is None:
                        continue
                    flattened = np.asarray(contexts_ds[index], dtype=np.float32)
                    shape_array = np.asarray(shapes_ds[index], dtype=np.int64)
                    if shape_array.size == 0:
                        continue
                    shape = tuple(int(x) for x in shape_array.tolist())
                    tensor = torch.from_numpy(flattened.reshape(shape))
                    if tensor.dim() == 3 and tensor.size(0) == 1:
                        tensor = tensor.squeeze(0)
                    context_tensors.append(tensor.to(dtype=torch.float32))
                if not context_tensors:
                    skipped_contexts += 1
                    continue
                feature = {
                    "question": question,
                    "answer": answers[0],
                    "context_embeddings": context_tensors,
                }
                instances.append(EvaluationInstance(feature=feature, references=answers, query_id=query_id))
            pending_examples = []
            pending_vectors = []

        for example in tqdm(raw_examples, desc="Preparing evaluation data"):
            question = example.get("question") or example.get("query") or ""
            answers_payload = example.get("answers")
            answer_texts: Sequence[str] = []
            if isinstance(answers_payload, dict):
                texts = answers_payload.get("text") or answers_payload.get("answers")
                if isinstance(texts, (list, tuple)):
                    answer_texts = [str(t) for t in texts if isinstance(t, str) and t.strip()]
            if not question or not answer_texts:
                continue
            query_id_raw = example.get("query_id")
            if query_id_raw is None:
                continue
            query_id = _to_str_doc_id(query_id_raw)
            vector = query_vectors.get(query_id)
            if vector is None:
                skipped_embeddings += 1
                continue
            pending_examples.append((query_id, question, answer_texts))
            pending_vectors.append(vector)
            if len(pending_examples) >= args.retriever_batch_size:
                process_pending()
                if args.max_examples is not None and len(instances) >= args.max_examples:
                    break
        if args.max_examples is None or len(instances) < args.max_examples:
            process_pending()

    if args.max_examples is not None:
        instances = instances[: args.max_examples]

    stats = {
        "total_candidates": len(raw_examples),
        "prepared_instances": len(instances),
        "skipped_embeddings": skipped_embeddings,
        "skipped_contexts": skipped_contexts,
    }
    return instances, stats


def run_generation(
    args: EvaluationArgs,
    model: COCOM,
    instances: List[EvaluationInstance],
) -> Tuple[List[str], float]:
    if not instances:
        raise EvaluationError("No evaluation instances available after preprocessing")

    collator = RAGDataCollator(
        tokenizer=model.decoder_tokenizer,
        top_k=args.top_k,
        decoder_max_length=args.decoder_max_length,
    )

    device = args.device
    predictions: List[str] = []
    total_time = 0.0

    for start in range(0, len(instances), args.batch_size):
        batch_instances = instances[start : start + args.batch_size]
        features = [instance.feature for instance in batch_instances]
        batch_inputs = collator(features)

        dec_input_ids = batch_inputs["dec_input_ids"].to(device)
        dec_attention_mask = batch_inputs["dec_attention_mask"].to(device)
        context_embeddings = batch_inputs["context_embeddings"].to(
            device=device, dtype=model.decoder.dtype
        )
        context_lengths = batch_inputs["context_lengths"].to(device)
        context_indices = batch_inputs["context_indices"].to(device)

        synchronize_if_needed(device)
        start_time = time.perf_counter()
        with torch.no_grad():
            inputs_embeds = model.replace_embeddings(
                compressed_embs=context_embeddings,
                compressed_embs_lengths=context_lengths,
                dec_input_ids=dec_input_ids,
                indices=context_indices,
            )
            generated_ids = model.decoder.generate(
                inputs_embeds=inputs_embeds,
                attention_mask=dec_attention_mask,
                do_sample=False,
                top_p=None,
                max_new_tokens=args.max_new_tokens,
            )
        synchronize_if_needed(device)
        total_time += time.perf_counter() - start_time

        decoded = model.decoder_tokenizer.batch_decode(generated_ids, skip_special_tokens=True)
        cleaned = [clean_generated_text(text, model.decoder_tokenizer) for text in decoded]
        predictions.extend(cleaned)

    return predictions, total_time


def compute_f1(predictions: List[str], instances: List[EvaluationInstance]) -> float:
    scores: List[float] = []
    for prediction, instance in zip(predictions, instances):
        references = instance.references
        if not references:
            scores.append(0.0)
            continue
        per_reference = [f1_single(prediction, reference) for reference in references]
        scores.append(max(per_reference) if per_reference else 0.0)
    return float(np.mean(scores)) if scores else 0.0


def main() -> None:
    args = parse_args()

    ensure_exists(args.contexts_path, "Context store")
    ensure_exists(args.embeddings_path, "Document embeddings")
    ensure_exists(args.queries_path, "Queries JSON")
    ensure_exists(args.answers_path, "Answers JSON")
    ensure_exists(args.query_embeddings_path, "Query embeddings")

    print(f"Loading COCOM model from Hugging Face: {args.model_name}")
    dtype = torch.bfloat16 if args.device.type != "cpu" else torch.float32
    model = COCOM.from_pretrained(args.model_name, torch_dtype=dtype, trust_remote_code=True)
    model.to(args.device)
    model.eval()
    model.generation_top_k = args.top_k

    print("Loading retrieval artefacts...")
    context_index = load_context_store(args.contexts_path)
    retriever = load_retriever(args.embeddings_path, args.docs_path)
    query_vectors, _ = load_query_embedding_store(args.query_embeddings_path)

    instances, stats = select_examples(args, retriever, query_vectors, context_index)
    print(
        "Prepared {prepared} evaluation instances (from {total} candidates, "
        "skipped {skip_emb} without embeddings, {skip_ctx} without contexts).".format(
            prepared=stats["prepared_instances"],
            total=stats["total_candidates"],
            skip_emb=stats["skipped_embeddings"],
            skip_ctx=stats["skipped_contexts"],
        )
    )

    predictions, total_time = run_generation(args, model, instances)
    mean_time = total_time / len(instances)
    f1 = compute_f1(predictions, instances)

    print("\n=== Evaluation summary ===")
    print(f"Examples evaluated: {len(instances)}")
    print(f"Total generation time: {total_time:.2f} seconds")
    print(f"Average generation time per example: {mean_time:.3f} seconds")
    print(f"Mean token-level F1: {f1:.4f}")

    print("\nSample predictions:")
    for idx, (instance, prediction) in enumerate(zip(instances[:3], predictions[:3])):
        print(f"[{idx}] Query ID: {instance.query_id}")
        print(f"    Question: {instance.feature['question']}")
        print(f"    Prediction: {prediction}")
        print(f"    Reference answers: {instance.references}")


if __name__ == "__main__":
    main()
